import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/containers/Navbar";
import Footer from "@/containers/Footer";
import SocialMediaSticky from "@/containers/ChatContacts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="text-slate-900 antialiased scroll-smooth">
      <body className={inter.className}>
        <Navbar />
        {children}
        <SocialMediaSticky />
        <Footer />
      </body>
    </html>
  );
}
